name: test render-web
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: install deps
        run: npm install
      - run: npm run test